import {
  Landmark,
  Briefcase,
  GraduationCap,
  HeartPulse,
  Car,
  Home,
  Baby,
  ReceiptText,
  Sigma,
  CalendarDays,
  Code2,
  Ruler,
  ShoppingCart,
  Trophy,
  ShieldCheck,
  Plane,
  Sparkles,
  Scale,
  Dices,
  Atom,
} from "lucide-react";
import type { Category } from "./types";

export const categories: Category[] = [
  {
    slug: "finansal",
    title: "Finansal Hesaplamalar",
    description: "KDV, faiz, kredi, mevduat, döviz ve daha fazlası.",
    icon: Landmark,
    tint: "text-blue-600 bg-blue-50 dark:bg-blue-500/10",
  },
  {
    slug: "maas",
    title: "Maaş ve Çalışma",
    description: "Brüt-net maaş, kıdem ve ihbar tazminatı hesaplamaları.",
    icon: Briefcase,
    tint: "text-indigo-600 bg-indigo-50 dark:bg-indigo-500/10",
  },
  {
    slug: "egitim",
    title: "Eğitim Hesaplamaları",
    description: "Not ortalaması, AGNO, GPA, TYT-AYT ve sınav hesapları.",
    icon: GraduationCap,
    tint: "text-violet-600 bg-violet-50 dark:bg-violet-500/10",
  },
  {
    slug: "sinav",
    title: "Sınav Puanı",
    description: "YKS (TYT/AYT), KPSS, LGS, DGS, YDS, ALES puan hesaplayıcıları.",
    icon: Trophy,
    tint: "text-yellow-600 bg-yellow-50 dark:bg-yellow-500/10",
  },
  {
    slug: "saglik",
    title: "Sağlık ve Beslenme",
    description: "BMI, kalori, ideal kilo, su ihtiyacı ve yağ oranı.",
    icon: HeartPulse,
    tint: "text-rose-600 bg-rose-50 dark:bg-rose-500/10",
  },
  {
    slug: "arac",
    title: "Araç ve Yakıt",
    description: "Yakıt maliyeti, tüketim, MTV ve yol masrafı hesabı.",
    icon: Car,
    tint: "text-orange-600 bg-orange-50 dark:bg-orange-500/10",
  },
  {
    slug: "ev-yasam",
    title: "Ev ve Yaşam",
    description: "Elektrik, su, doğalgaz faturası ve konut kredisi.",
    icon: Home,
    tint: "text-teal-600 bg-teal-50 dark:bg-teal-500/10",
  },
  {
    slug: "hamilelik",
    title: "Hamilelik ve Bebek",
    description: "Gebelik haftası, tahmini doğum tarihi ve bebek gelişimi.",
    icon: Baby,
    tint: "text-pink-600 bg-pink-50 dark:bg-pink-500/10",
  },
  {
    slug: "vergi",
    title: "Vergi Hesaplamaları",
    description: "Gelir vergisi, damga vergisi ve kurumlar vergisi.",
    icon: ReceiptText,
    tint: "text-emerald-600 bg-emerald-50 dark:bg-emerald-500/10",
  },
  {
    slug: "matematik",
    title: "Matematik Hesaplamaları",
    description: "Yüzde, üslü sayı, karekök, EBOB-EKOK, faktöriyel ve geometri.",
    icon: Sigma,
    tint: "text-cyan-600 bg-cyan-50 dark:bg-cyan-500/10",
  },
  {
    slug: "donusturucu",
    title: "Birim Dönüştürücüler",
    description: "Uzunluk, ağırlık, sıcaklık, alan, hacim, hız, veri ve zaman çevirici.",
    icon: Ruler,
    tint: "text-sky-600 bg-sky-50 dark:bg-sky-500/10",
  },
  {
    slug: "ticari",
    title: "Ticari Hesaplamalar",
    description: "Kâr marjı, iskonto, desi/kargo ve ticari hesaplar.",
    icon: ShoppingCart,
    tint: "text-fuchsia-600 bg-fuchsia-50 dark:bg-fuchsia-500/10",
  },
  {
    slug: "sigorta",
    title: "Sigorta Hesaplamaları",
    description: "DASK, kasko, trafik sigortası basamak hesaplayıcıları.",
    icon: ShieldCheck,
    tint: "text-lime-600 bg-lime-50 dark:bg-lime-500/10",
  },
  {
    slug: "hukuki",
    title: "Hukuki Hesaplamalar",
    description: "Yasal faiz, arabuluculuk, tapu harcı ve kira artışı hesapları.",
    icon: Scale,
    tint: "text-stone-600 bg-stone-100 dark:bg-stone-500/10",
  },
  {
    slug: "sans-karar",
    title: "Şans & Karar Araçları",
    description: "Karar çarkı, yazı-tura, zar atma, ne yiyeyim? — eğlenceli karar verme.",
    icon: Dices,
    tint: "text-pink-600 bg-pink-50 dark:bg-pink-500/10",
  },
  {
    slug: "bilimsel",
    title: "Bilimsel & Kompleks Hesaplamalar",
    description: "Formül ifade hesaplayıcı, denklem sistemi, matris, fizik ve kimya.",
    icon: Atom,
    tint: "text-emerald-600 bg-emerald-50 dark:bg-emerald-500/10",
  },
  {
    slug: "seyahat",
    title: "Seyahat Hesaplamaları",
    description: "Elektrikli araç şarj maliyeti, taksi ücreti, yakıt.",
    icon: Plane,
    tint: "text-purple-600 bg-purple-50 dark:bg-purple-500/10",
  },
  {
    slug: "yasam",
    title: "Yaşam ve Diğer",
    description: "Burç, kuşak, zekat, klima BTU, sigara maliyeti.",
    icon: Sparkles,
    tint: "text-red-600 bg-red-50 dark:bg-red-500/10",
  },
  {
    slug: "tarih",
    title: "Tarih Hesaplamaları",
    description: "Yaş hesabı, iki tarih arası gün ve gün ekleme.",
    icon: CalendarDays,
    tint: "text-amber-600 bg-amber-50 dark:bg-amber-500/10",
  },
  {
    slug: "gelistirici",
    title: "Geliştirici Araçları",
    description: "JSON formatlayıcı, Base64, UUID ve dönüştürücüler.",
    icon: Code2,
    tint: "text-slate-600 bg-slate-100 dark:bg-slate-500/10",
  },
];

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
